<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Batch;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class BatchController extends Controller
{
    /** List generated batches, paginated. Scoped to reseller/seller if needed. */
    public function index(Request $request): JsonResponse
    {
        $actor = $request->user();
        // serial_start/serial_end let the frontend show (and prefill an Allocate
        // Voucher action with) the batch's printed card range, e.g. 26-000001–26-000100.
        $q = Batch::withMin('vouchers as serial_start', 'serial_number')
            ->withMax('vouchers as serial_end', 'serial_number')
            ->with(['plan:id,name,selling_price,data_gb,package_type', 'generatedBy:id,username,role']);

        if ($actor->isReseller()) {
            // Resellers see batches generated by themselves or their downline.
            $q->where(fn ($x) => $x->where('generated_by', $actor->id)
                ->orWhereIn('generated_by', fn ($y) => $y->select('id')->from('users')->where('parent_id', $actor->id))
            );
        } elseif ($actor->isSeller()) {
            $q->where('generated_by', $actor->id);
        }

        if ($p = $request->query('plan_id')) {
            $q->where('plan_id', $p);
        }
        if ($code = $request->query('batch_code')) {
            $q->where('batch_code', 'like', "%$code%");
        }

        return $this->ok($q->latest()->paginate($request->integer('per_page', 20)));
    }
}
